node 'jenkins-lis-builder' {
  notice("${fqdn} is puppet managed by moneypenny.openstack.tld")
  class{'profiles::shipyard':}
  package{[
    # Light UI for Mgmt
    'blackbox','tightvncserver','xterm','virt-manager',
    # httpasswd file management tools
    'apache2-utils',
    # Beaker Requrements
    'make','ruby-dev','libxml2-dev','libxslt1-dev','g++','zlib1g-dev',
    # Puppet Lint Syntax testing
    'puppet-lint',
  ]:
    ensure          => 'latest'
  } ->

  class {'jenkins':
    version                              => 'latest',
    lts                                  => false,
    executors                            => 8,
    install_java                         => true,
    configure_firewall                   => true,
    config_hash                          => {
      'HTTP_PORT'                        => {'value' => '9000' }
    },
    plugin_hash                          => {
      'antisamy-markup-formatter'        => { 'version' => 'latest' },
      'authentication-tokens'            => { 'version' => 'latest' },
      'ansicolor'                        => { 'version' => 'latest' },
      'backup'                           => { 'version' => 'latest' },
      'build-alias-setter'               => { 'version' => 'latest' },
      'build-blocker-plugin'             => { 'version' => 'latest' },
      'build-cause-run-condition'        => { 'version' => 'latest' },
      'build-env-propagator'             => { 'version' => 'latest' },
      'build-environment'                => { 'version' => 'latest' },
      'build-failure-analyzer'           => { 'version' => 'latest' },
      'build-flow-extensions-plugin'     => { 'version' => 'latest' },
      'build-flow-plugin'                => { 'version' => 'latest' },
      'build-flow-test-aggregator'       => { 'version' => 'latest' },
      'build-flow-toolbox-plugin'        => { 'version' => 'latest' },
      'build-history-metrics-plugin'     => { 'version' => 'latest' },
      'build-keeper-plugin'              => { 'version' => 'latest' },
      'build-line'                       => { 'version' => 'latest' },
      'build-metrics'                    => { 'version' => 'latest' },
      'build-monitor-plugin'             => { 'version' => 'latest' },
      'build-name-setter'                => { 'version' => 'latest' },
      'build-pipeline-plugin'            => { 'version' => 'latest' },
      'build-requester'                  => { 'version' => 'latest' },
      'build-timeout'                    => { 'version' => 'latest' },
      'build-timestamp'                  => { 'version' => 'latest' },
      'build-view-column'                => { 'version' => 'latest' },
      'buildgraph-view'                  => { 'version' => 'latest' },
      'built-on-column'                  => { 'version' => 'latest' },
      'cvs'                              => { 'version' => 'latest' },
      'cloud-stats'                      => { 'version' => 'latest' },
      'copyartifact'                     => { 'version' => 'latest' },
      'compact-columns'                  => { 'version' => 'latest' },
      'config-file-provider'             => { 'version' => 'latest' },
      'configure-job-column-plugin'      => { 'version' => 'latest' },
      'console-column-plugin'            => { 'version' => 'latest' },
      'custom-job-icon'                  => { 'version' => 'latest' },
      'dashboard-view'                   => { 'version' => 'latest' },
      'deployment-notification'          => { 'version' => 'latest' },
      'display-url-api'                  => { 'version' => 'latest' },
      'docker-workflow'                  => { 'version' => 'latest' },
      'docker-traceability'              => { 'version' => 'latest' },
      'docker-plugin'                    => { 'version' => 'latest' },
      'docker-custom-build-environment'  => { 'version' => 'latest' },
      'docker-commons'                   => { 'version' => 'latest' },
      'docker-build-step'                => { 'version' => 'latest' },
      'docker-build-publish'             => { 'version' => 'latest' },
      'gerrit'                           => { 'version' => 'latest' },
      'gerrit-trigger'                   => { 'version' => 'latest' },
      'github'                           => { 'version' => 'latest' },
      'github-api'                       => { 'version' => 'latest' },
      'git'                              => { 'version' => 'latest' },
      'git-changelog'                    => { 'version' => 'latest' },
      'git-client'                       => { 'version' => 'latest' },
      'git-chooser-alternative'          => { 'version' => 'latest' },
      'git-notes'                        => { 'version' => 'latest' },
      'git-parameter'                    => { 'version' => 'latest' },
      'git-tag-message'                  => { 'version' => 'latest' },
      'github-branch-source'             => { 'version' => 'latest' },
      'github-pullrequest'               => { 'version' => 'latest' },
      'global-build-stats'               => { 'version' => 'latest' },
      'global-post-script'               => { 'version' => 'latest' },
      'global-variable-string-parameter' => { 'version' => 'latest' },
      'icon-shim'                        => { 'version' => 'latest' },
      'jenkins-multijob-plugin'          => { 'version' => 'latest' },
      'javadoc'                          => { 'version' => 'latest' },
      'junit'                            => { 'version' => 'latest' },
      'job-restrictions'                 => { 'version' => 'latest' },
      'job-parameter-summary'            => { 'version' => 'latest' },
      'jobtemplates'                     => { 'version' => 'latest' },
      'jobtype-column'                   => { 'version' => 'latest' },
      'libvirt-slave'                    => { 'version' => 'latest' },
      'logging'                          => { 'version' => 'latest' },
      'mailer'                           => { 'version' => 'latest' },
      'mapdb-api'                        => { 'version' => 'latest' },
      'matrix-auth'                      => { 'version' => 'latest' },
      'matrix-project'                   => { 'version' => 'latest' },
      'maven-plugin'                     => { 'version' => 'latest' },
      'mission-control-view'             => { 'version' => 'latest' },
      'modernstatus'                     => { 'version' => 'latest' },
      'multiple-scms'                    => { 'version' => 'latest' },
      'mysql-job-databases'              => { 'version' => 'latest' },
      'nested-view'                      => { 'version' => 'latest' },
      'network-monitor'                  => { 'version' => 'latest' },
      'openstack-cloud'                  => { 'version' => 'latest' },
      'pam-auth'                         => { 'version' => 'latest' },
      'parallel-test-executor'           => { 'version' => 'latest' },
      'parameterized-trigger'            => { 'version' => 'latest' },
      'powershell'                       => { 'version' => 'latest' },
      'port-allocator'                   => { 'version' => 'latest' },
      'puppet'                           => { 'version' => 'latest' },
      'postbuildscript'                  => { 'version' => 'latest' },
      'prereq-buildstep'                 => { 'version' => 'latest' },
      'project-build-times'              => { 'version' => 'latest' },
      'project-stats-plugin'             => { 'version' => 'latest' },
      'promoted-builds'                  => { 'version' => 'latest' },
      'python'                           => { 'version' => 'latest' },
      'run-condition'                    => { 'version' => 'latest' },
      'ruby-runtime'                     => { 'version' => 'latest' },
      'resource-disposer'                => { 'version' => 'latest' },
      'saferestart'                      => { 'version' => 'latest' },
      'saltstack'                        => { 'version' => 'latest' },
      'ssh-slaves'                       => { 'version' => 'latest' },
      'ssh-credentials'                  => { 'version' => 'latest' },
      'scp'                              => { 'version' => 'latest' },
      'scm-api'                          => { 'version' => 'latest' },
      'sidebar-link'                     => { 'version' => 'latest' },
      'swarm'                            => { 'version' => 'latest' },
      'subversion'                       => { 'version' => 'latest' },
      'script-security'                  => { 'version' => 'latest' },
      'slave-prerequisites'              => { 'version' => 'latest' },
      'slave-proxy'                      => { 'version' => 'latest' },
      'slave-setup'                      => { 'version' => 'latest' },
      'slave-squatter'                   => { 'version' => 'latest' },
      'slave-status'                     => { 'version' => 'latest' },
      'slave-utilization-plugin'         => { 'version' => 'latest' },
      'structs'                          => { 'version' => 'latest' },
      'stackhammer'                      => { 'version' => 'latest' },
      'started-by-envvar'                => { 'version' => 'latest' },
      'status-view'                      => { 'version' => 'latest' },
      'statusmonitor'                    => { 'version' => 'latest' },
      'systemloadaverage-monitor'        => { 'version' => 'latest' },
      'tfs'                              => { 'version' => 'latest' },
      'thinBackup'                       => { 'version' => 'latest' },
      'timestamper'                      => { 'version' => 'latest' },
      'token-macro'                      => { 'version' => 'latest' },
      'tracking-git'                     => { 'version' => 'latest' },
      'tracking-svn'                     => { 'version' => 'latest' },
      'translation'                      => { 'version' => 'latest' },
      'uptime'                           => { 'version' => 'latest' },
      'workflow-basic-steps'             => { 'version' => 'latest' },
      'workflow-cps'                     => { 'version' => 'latest' },
      'workflow-durable-task-step'       => { 'version' => 'latest' },
      'workflow-scm-step'                => { 'version' => 'latest' },
      'windows-azure-storage'            => { 'version' => 'latest' },
      'windows-exe-runner'               => { 'version' => 'latest' },
      'windows-slaves'                   => { 'version' => 'latest' },
      'vncrecorder'                      => { 'version' => 'latest' },
      'vncviewer'                        => { 'version' => 'latest' },
    },
  }

  git::config { 'user.name':
    value => 'hypervci',
  }

  git::config { 'user.email':
    value => 'hyper-v_ci@microsoft.com',
  }
}
